In [21]:
import pandas as pd

df = pd.read_excel("US_Budget_vs_Actual_29000.xlsx")

df.head()

,date,state,region,product_line,product,budget_revenue,actual_revenue,quantity,standard_price_usd,selling_price_usd,discount_pct,cogs_per_unit_usd,marketing_spend_usd
0,2024-05-01,Illinois,Midwest,Furniture,Dining Table,175300.32,168474.63,169,1037.28,850.57,18,649.71,9189.49
1,2025-08-23,Pennsylvania,Northeast,Electronics,Headphones,9331.22,8107.76,30,270.47,213.67,21,194.05,521.00
2,2025-11-26,Ohio,Midwest,Fashion,Backpack,253430.35,273702.16,99,1765.45,1677.18,5,831.12,15239.57
3,2024-03-19,Illinois,Midwest,Sports,Football,48273.12,53494.29,84,574.68,540.20,6,304.01,3149.27
4,2024-01-26,Michigan,Midwest,Fashion,Smart Watch,22746.93,24476.08,33,765.89,712.28,7,331.76,1254.94

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29000 entries, 0 to 28999
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   date                 29000 non-null  object
 1   state                29000 non-null  object
 2   region               29000 non-null  object
 3   product_line         29000 non-null  object
 4   product              29000 non-null  object
 5   budget_revenue       29000 non-null  float64
 6   actual_revenue       29000 non-null  float64
 7   quantity             29000 non-null  int64
 8   standard_price_usd   29000 non-null  float64
 9   selling_price_usd    29000 non-null  float64
 10  discount_pct         29000 non-null  int64
 11  cogs_per_unit_usd    29000 non-null  float64
 12  marketing_spend_usd  29000 non-null  float64
dtypes: float64(6), int64(2), object(5)
memory usage: 2.9+ MB

In [23]:
df.describe()

,budget_revenue,actual_revenue,quantity,standard_price_usd,selling_price_usd,discount_pct,cogs_per_unit_usd,marketing_spend_usd
count,29000.000000,29000.000000,29000.000000,29000.000000,29000.000000,29000.000000,29000.000000,29000.000000
mean,117976.068533,117250.200362,115.081241,936.547169,817.800903,12.678379,512.415260,6456.422657
std,97939.020663,98295.291554,60.888349,496.852303,440.816523,7.244879,297.122213,5883.488341
min,815.940000,875.940000,10.000000,80.110000,56.830000,3.000000,29.380000,30.860000
25%,39185.070000,38554.525000,62.000000,505.712500,437.527500,7.000000,265.000000,2006.292500
50%,91012.400000,89718.760000,115.000000,937.375000,813.970000,11.000000,489.880000,4702.390000
75%,173416.862500,171515.105000,168.000000,1366.627500,1184.947500,16.000000,721.740000,9167.400000
max,615673.820000,686427.300000,220.000000,1799.860000,1745.180000,30.000000,1421.000000,53790.110000

In [24]:
df.describe(include='all')

,date,state,region,product_line,product,budget_revenue,actual_revenue,quantity,standard_price_usd,selling_price_usd,discount_pct,cogs_per_unit_usd,marketing_spend_usd
count,29000,29000,29000,29000,29000,29000.000000,29000.000000,29000.000000,29000.000000,29000.000000,29000.000000,29000.000000,29000.000000
unique,731,16,4,5,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2024-01-27,Pennsylvania,Northeast,Sports,Jacket,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,59,1860,7279,5853,1223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,117976.068533,117250.200362,115.081241,936.547169,817.800903,12.678379,512.415260,6456.422657
std,NaN,NaN,NaN,NaN,NaN,97939.020663,98295.291554,60.888349,496.852303,440.816523,7.244879,297.122213,5883.488341
min,NaN,NaN,NaN,NaN,NaN,815.940000,875.940000,10.000000,80.110000,56.830000,3.000000,29.380000,30.860000
25%,NaN,NaN,NaN,NaN,NaN,39185.070000,38554.525000,62.000000,505.712500,437.527500,7.000000,265.000000,2006.292500
50%,NaN,NaN,NaN,NaN,NaN,91012.400000,89718.760000,115.000000,937.375000,813.970000,11.000000,489.880000,4702.390000
75%,NaN,NaN,NaN,NaN,NaN,173416.862500,171515.105000,168.000000,1366.627500,1184.947500,16.000000,721.740000,9167.400000
max,NaN,NaN,NaN,NaN,NaN,615673.820000,686427.300000,220.000000,1799.860000,1745.180000,30.000000,1421.000000,53790.110000

In [25]:
df.isnull().sum()

date                   0
state                  0
region                 0
product_line           0
product                0
budget_revenue         0
actual_revenue         0
quantity               0
standard_price_usd     0
selling_price_usd      0
discount_pct           0
cogs_per_unit_usd      0
marketing_spend_usd    0
dtype: int64

In [26]:
df.shape

(29000, 13)

In [27]:
df.duplicated().sum()

np.int64(0)

In [28]:
df.columns

Index(['date', 'state', 'region', 'product_line', 'product', 'budget_revenue',
       'actual_revenue', 'quantity', 'standard_price_usd', 'selling_price_usd',
       'discount_pct', 'cogs_per_unit_usd', 'marketing_spend_usd'],
      dtype='object')

In [29]:
df["variance_usd"] = df["actual_revenue"] - df["budget_revenue"]

In [30]:
df.head()

,date,state,region,product_line,product,budget_revenue,actual_revenue,quantity,standard_price_usd,selling_price_usd,discount_pct,cogs_per_unit_usd,marketing_spend_usd,variance_usd
0,2024-05-01,Illinois,Midwest,Furniture,Dining Table,175300.32,168474.63,169,1037.28,850.57,18,649.71,9189.49,-6825.69
1,2025-08-23,Pennsylvania,Northeast,Electronics,Headphones,9331.22,8107.76,30,270.47,213.67,21,194.05,521.00,-1223.46
2,2025-11-26,Ohio,Midwest,Fashion,Backpack,253430.35,273702.16,99,1765.45,1677.18,5,831.12,15239.57,20271.81
3,2024-03-19,Illinois,Midwest,Sports,Football,48273.12,53494.29,84,574.68,540.20,6,304.01,3149.27,5221.17
4,2024-01-26,Michigan,Midwest,Fashion,Smart Watch,22746.93,24476.08,33,765.89,712.28,7,331.76,1254.94,1729.15

In [31]:
df["variance_pct"] = (
    df["variance_usd"] / df["budget_revenue"]
) * 100

In [32]:
df.head()

,date,state,region,product_line,product,budget_revenue,actual_revenue,quantity,standard_price_usd,selling_price_usd,discount_pct,cogs_per_unit_usd,marketing_spend_usd,variance_usd,variance_pct
0,2024-05-01,Illinois,Midwest,Furniture,Dining Table,175300.32,168474.63,169,1037.28,850.57,18,649.71,9189.49,-6825.69,-3.893712
1,2025-08-23,Pennsylvania,Northeast,Electronics,Headphones,9331.22,8107.76,30,270.47,213.67,21,194.05,521.00,-1223.46,-13.111469
2,2025-11-26,Ohio,Midwest,Fashion,Backpack,253430.35,273702.16,99,1765.45,1677.18,5,831.12,15239.57,20271.81,7.998967
3,2024-03-19,Illinois,Midwest,Sports,Football,48273.12,53494.29,84,574.68,540.20,6,304.01,3149.27,5221.17,10.815895
4,2024-01-26,Michigan,Midwest,Fashion,Smart Watch,22746.93,24476.08,33,765.89,712.28,7,331.76,1254.94,1729.15,7.601685

In [33]:
df["date"] = pd.to_datetime(df["date"])

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29000 entries, 0 to 28999
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   date                 29000 non-null  datetime64[ns]
 1   state                29000 non-null  object
 2   region               29000 non-null  object
 3   product_line         29000 non-null  object
 4   product              29000 non-null  object
 5   budget_revenue       29000 non-null  float64
 6   actual_revenue       29000 non-null  float64
 7   quantity             29000 non-null  int64
 8   standard_price_usd   29000 non-null  float64
 9   selling_price_usd    29000 non-null  float64
 10  discount_pct         29000 non-null  int64
 11  cogs_per_unit_usd    29000 non-null  float64
 12  marketing_spend_usd  29000 non-null  float64
 13  variance_usd         29000 non-null  float64
 14  variance_pct         29000 non-null  float64
dtypes: datetime64[ns](1), float64(8), int64(2), object(4)
memory usage: 3.3+ MB

In [35]:
!pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\harshitha\anaconda3\lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\users\harshitha\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\harshitha\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\harshitha\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)

In [36]:
from sqlalchemy import create_engine


username = "postgres"      
password = "password" 
host = "localhost"         
port = "5432"              
database = "budget_vs_actual"    

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")


table_name = "budgetvsactual"  
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'budgetvsactual' in database 'budget_vs_actual'.